core/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.index, name='index'),
  path('about/', views.about, name='about'),

  path('users/', views.users, name='users'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    # hot reload
    path("__reload__/", include("django_browser_reload.urls")),
    # admin
    path('admin/', admin.site.urls),

    # rise_group
    path('', include(('rise_group.urls', 'rise_group'), namespace='rise_group')),

    # todo
    # path('todo/', include('todo.urls')),

    # users
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('login/', views.login_view, name='login-view'),
  # path('login-route/', views.login_route, name='login-route'),
  path('logout/', views.logout, name='logout-view'),
  path('forgot-password/', views.forgot_password_view, name='forgot-password-view'),
  path('reset-password/', views.reset_password_view, name='reset-password-view'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

# Custom user model extending AbstractUser
class CustomUser(AbstractUser):
  # add additional fields in here
  bio = models.TextField(blank=True, null=True)

users/forms.py
from django import forms

class LoginForm(forms.Form):
    email = forms.EmailField(
        required=True,
        error_messages={
            'required': 'وارد کردن ایمیل الزامی است.',
            'invalid': 'فرمت ایمیل معتبر نیست.',
        }
    )
    password = forms.CharField(
        widget=forms.PasswordInput,
        required=True,
        error_messages={
            'required': 'رمز عبور را وارد کنید.',
        }
    )
    remember = forms.BooleanField(
        required=False
    )

users/views.py
from django.shortcuts import render
# form validation
from .forms import LoginForm
# time
# from datetime import datetime
from datetime import timedelta
from django.utils import timezone
# notification
from django.contrib import messages

# Create your views here.
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required

# def login_view(request):
#   if request.method == 'POST':
#     form = AuthenticationForm(data=request.POST)
#     if form.is_valid():
#       user = form.get_user()
#       login(request, user)
#       return redirect('index')
#   else:
#     form = AuthenticationForm()
#   return render(request, 'users/login.html', {'form': form})

def login_view(request):

  # on form submit
  if request.method == 'POST':
    print("*****************55", request.POST)
    form = LoginForm(request.POST)
    
    if form.is_valid():
      # redirect to: rise_group:index
      return redirect('rise_group:index-view')

    else:
      request.session['form_errors'] = form.errors
      request.session['form_data'] = request.POST.dict()
      return redirect('users:login-view')  # redirect to GET


  # on GET : reset errors
  else:
    # Rebuild form from session if there were errors
    errors = request.session.pop('form_errors', None)
    data = request.session.pop('form_data', None)
    if errors and data:
      form = LoginForm(data)
      form._errors = errors  # manually assign errors
    else:
      form = LoginForm()
  
  print("*****************")
  print(form.errors)
  return render(request, 'users/login.html', {'form': form})

def logout(request):
  logout(request)
  return redirect('login')

# forget password view
def forgot_password_view(request):

  if request.method == 'POST':
    # redirect to reset-password
    return redirect('users:reset-password-view')

  return render(request, 'users/forgot-password.html')

# reset password view
def reset_password_view(request):

  # generate a date and add 20 seconds to it
  # otp_expiry_time = datetime.now() + timedelta(seconds=20)

  otp_expiry_time = timezone.now() + timedelta(seconds=120)

  if request.method == 'POST':
    # set a message
    messages.success(request, "رمز عبور شما با موفقیت تغییر کرد")
    # messages.error(request, "رمز عبور شما با موفقیت تغییر نکرد")
    #messages.info(request, "رمز عبور شما با موفقیت تغییر کرد")

    print('**88')
    return redirect("users:reset-password-view")

  return render(request, 'users/reset-password.html', {'otp_expiry_time': otp_expiry_time.isoformat()})

# def signup_view(request):
#   if request.method == 'POST':
#     form = UserCreationForm(request.POST)
#     if form.is_valid():
#       user = form.save()
#       login(request, user)
#       return redirect('home')
#   else:
#       form = UserCreationForm()
#   return render(request, 'authapp/signup.html', {'form': form})

# @login_required
# def profile_view(request):
#   return render(request, 'authapp/profile.html')

users/templates/users/components/_ForgotPassword.html
{% load static %}

{% firstof form.email.errors|yesno:"ring-red-500 ring-2 form-input, form-input" as email_error_class %}
{% firstof form.email.errors|yesno:"ring-red-500 ring-2 form-input, form-input" as password_error_class %}

<div class="relative form-bg p-3 md:p-8 max-w-2xl #mx-auto min-w-full md:min-w-[500px] overflow-hidden z-0">

  <h3 class="text-2xl font-bold mb-8 text-center">
  بازیابی رمز عبور
  </h3>
  
  <p class="text-lg text-center text-gray-400 mb-6">
  برای بازیابی رمز عبور، ایمیل خود را وارد کنید تا کد تایید برای شما ارسال شود.
  </p>

  <form 
  method="post"
  action="{% url 'users:reset-password-view' %}"
  class="flex flex-col gap-2"
  novalidate
  >
    {% comment %} required for post {% endcomment %}
    {% csrf_token %}

    {% comment %} we use this to know what action to take: create or update {% endcomment %}
    <input type="hidden" name="action" value="login">

    <div class="mb-5 flex flex-col gap-2">
      {% include 'elements/_Label.html' with title='ایمیل' for='email' %}
      {% include 'elements/_Input.html' with id='email' type='email' name='email' placeholder='ایمیل را وارد کنید' required=True autocomplete="on" classes=email_error_class icon="user-2" value="{{ form.email.value }}"  %}

      {% comment %} <div>{{form.email.errors}}</div> {% endcomment %}
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          <span class="text-red-500 text-sm">
            {{ error }}
          </span>
        {% endfor %}
      {% endif %}
    </div>

    {% include 'elements/_Button.html' with type='submit' text='ارسال کد تایید' size='lg' classes="form-btn self-center" %}
  </form>

  {% comment %} background image {% endcomment %}
  <img src="{% static 'users/images/auth-bg.png' %}" alt="auth-bg" class="absolute -top-1/2 left-0 right-0 -z-10" />
</div>

users/templates/users/components/_LoginForm.html
{% load static %}

{% firstof form.email.errors|yesno:"ring-red-500 ring-2 form-input, form-input" as email_error_class %}
{% firstof form.email.errors|yesno:"ring-red-500 ring-2 form-input, form-input" as password_error_class %}

<div class="relative form-bg p-3 md:p-8 max-w-2xl #mx-auto min-w-full md:min-w-[500px] overflow-hidden z-0">

  <h3 class="text-2xl font-bold mb-8 text-center">
  ورود
  </h3>
  {% comment %} submits to /todo {% endcomment %}

  <form 
  method="post"
  action="{% url 'users:login-view' %}"
  class="flex flex-col gap-2"
  novalidate
  >
    {% comment %} required for post {% endcomment %}
    {% csrf_token %}

    {% comment %} we use this to know what action to take: create or update {% endcomment %}
    <input type="hidden" name="action" value="login">

    <div class="mb-5 flex flex-col gap-2">
      {% include 'elements/_Label.html' with title='ایمیل' for='email' %}
      {% include 'elements/_Input.html' with id='email' type='email' name='email' placeholder='ایمیل را وارد کنید' required=True autocomplete="on" classes=email_error_class icon="user-2" value="{{ form.email.value }}"  %}

      {% comment %} <div>{{form.email.errors}}</div> {% endcomment %}
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          <span class="text-red-500 text-sm">
            {{ error }}
          </span>
        {% endfor %}
      {% endif %}
    </div>

    <div class="mb-5 flex flex-col gap-2">
      {% include 'elements/_Label.html' with title='رمز عبور' for='password' %}
      {% include 'elements/_Input.html' with id='password' type='password' name='password' placeholder='رمز عبور را وارد کنید' required=True autocomplete="on" classes=password_error_class icon="user-2" value="{{ form.password.value }}"  %}

      {% if form.password.errors %}
        {% for error in form.password.errors %}
          <span class="text-red-500 text-sm">
            {{ error }}
          </span>
        {% endfor %}
      {% endif %}
    </div>
    
    <div class="flex items-center gap-2 justify-between mb-3">
      <div class="flex items-start gap-2">
        {% include 'elements/_Checkbox.html' with id='remember' name='remember'  %}
        {% include 'elements/_Label.html' with title='مرا به خاطر بسپار' for='remember' classes="mb-0" %}
        
      </div>
      <a href="{% url 'users:forgot-password-view' %}"><span class="text-sm font-bold text-gray-300 hover:text-gray-400 hover:cursor-pointer">رمز عبور را فراموش کرده ام</span></a>
    </div>
    
    {% include 'elements/_Button.html' with type='submit' text='وارد شوید' size='lg' classes="form-btn self-center"%}
  </form>

  {% comment %} background image {% endcomment %}
  <img src="{% static 'users/images/auth-bg.png' %}" alt="auth-bg" class="absolute -top-1/2 left-0 right-0 -z-10" />
</div>

users/templates/users/components/_ResetPasswordForm.html
{% load static %}

{% firstof form.email.errors|yesno:"ring-red-500 ring-2 form-input, form-input" as email_error_class %}
{% firstof form.email.errors|yesno:"ring-red-500 ring-2 form-input, form-input" as password_error_class %}

{% if messages|length > 0 %}
  <div 
  class="fixed top-5 right-5 z-50"
  
  >
    {% for message in messages %}
      {% include 'elements/_Toast.html' with message=message %}
    {% endfor %}
  </div>
{% endif %}

<div class="relative form-bg p-3 md:p-8 max-w-2xl #mx-auto min-w-full md:min-w-[500px] overflow-hidden z-0">

  <h3 class="text-2xl font-bold mb-8 text-center">
  بازیابی رمز عبور
  </h3>
  
  
  <div class="flex items-center gap-2">
    <span class="self-start">
    {% include 'elements/_Icon.html' with icon_name='tick-circle' classes='text-green-400' %}
    </span>
    <p class="text-lg text-center text-gray-400 mb-6">
    کدی که به ایمیل you@example.com ارسال شده را وارد کنید و رمز جدید خود را تنظیم کنید.
    </p>
  </div>


  <form 
  method="post"
  action="{% url 'users:reset-password-view' %}"
  class="flex flex-col gap-4"
  novalidate
  x-init="init()"
  x-data="otpForm(6)"
  @submit="combineOtp()"
  >
    {% csrf_token %}

    {% comment %} we use this to know what action to take: create or update {% endcomment %}
    <input type="hidden" name="action" value="reset-password">

    <div class="flex flex-col gap-2" dir="ltr">
      <div class="flex gap-3 mb-3"> 
        
        <template 
        x-for="(digit, index) in otp"
        :key="index"
        >
          
          <input 
          :id="index"
          type="text" 
          maxlength="1"
          class="flex-1 bg-gray-50 border border-gray-300 text-gray-300 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-4 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 {{ classes }} form-input text-center" 
          autocomplete="off"
          :name="'otp_' + index"
          autocorrect="off"
          spellcheck="false"

          x-model="otp[index]"
          x-init="setRef($el, index)"
          @input="onInput(index, $event)"
          @keydown.backspace="onBackspace(index, $event)"
          />
        </template>
        
      </div>
      {% comment %} hidden input for otp {% endcomment %}
      <input type="hidden" name="otp" id="otp-full" :value="otp.join('')" />

      {% if form.otp.errors %}
        {% for error in form.otp.errors %}
          <span class="text-red-500 text-sm">
            {{ error }}
          </span>
        {% endfor %}
      {% endif %}
    </div>

    {% comment %} otp timer {% endcomment %}
    {% include 'elements/_OtpTimer.html' with otp_expiry_time=otp_expiry_time %}

    <div class="mb-5 flex flex-col gap-2">
      {% include 'elements/_Label.html' with title="رمز عبور جدید" for='password' %}
      {% include 'elements/_Input.html' with id='password' type='password' name='password' placeholder='رمز عبور جدید' required=True autocomplete="new-password" classes=password_error_class icon="user-2" value="{{ form.password.value }}"  %}

      {% if form.password.errors %}
        {% for error in form.password.errors %}
          <span class="text-red-500 text-sm">
            {{ error }}
          </span>
        {% endfor %}
      {% endif %}
    </div>

    <div class="mb-5 flex flex-col gap-2">
      {% include 'elements/_Label.html' with title="تکرار رمز عبور" for='repeat_password' %}
      {% include 'elements/_Input.html' with id='repeat_password' type='password' name='repeat_password' placeholder='تکرار رمز عبور' required=True autocomplete="new-password" classes=password_error_class icon="user-2" value="{{ form.repeat_password.value }}"  %}

      {% if form.repeat_password.errors %}
        {% for error in form.repeat_password.errors %}
          <span class="text-red-500 text-sm">
            {{ error }}
          </span>
        {% endfor %}
      {% endif %}
    </div>

    {% include 'elements/_Button.html' with type='submit' text='ارسال کد تایید' size='lg' classes="form-btn self-center"%}
  </form>

  {% comment %} background image {% endcomment %}
  <img src="{% static 'users/images/auth-bg.png' %}" alt="auth-bg" class="absolute -top-1/2 left-0 right-0 -z-10" />
</div>

<script type="text/javascript" defer>
  // this returns an object (alpineJS state)
  function otpForm(length) {

    //this is an alpineJs component
    return {
      otp: Array(length).fill(""),
      refs: {},

      setRef(el, index) {
        this.refs[index] = el;
      },

      init() {
        this.$nextTick(() => {
          this.refs?.[0]?.focus();
        });
      },

      combineOtp() {
        // This will be auto-populated in the hidden input via binding
      },

      onInput(index, event) {
        // digits only
        const value = event.target.value.replace(/[^0-9]/g, ""); 
        // set the right value in the right index
        this.otp[index] = value;

        if (value && index < this.otp.length - 1) {
          this.$nextTick(() => {
            this.refs?.[index + 1]?.focus();
          });
        }
      },

      // move to the previous input when backspace is pressed
      onBackspace(index, event) {
        // if the input is empty and we are not at the first index
        if (!this.otp[index] && index > 0) {
          this.$nextTick(() => {
            this.refs?.[index - 1]?.focus();
          });
        }
      },
    };
  }
</script>